---
# tasks file for ansible-role-openstack-common

- name: Setup repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck | default('no') }}"
    enabled: "{{ item.enabled | default('yes') }}"
    file: openstack
  with_items:
    - "{{ openstack_repos }}"
  when: openstack_repo_openstack

- name: Prepare hosts file for name resolution.
  template: src=hosts.j2 dest=/etc/hosts

- name: Install OpenStack base packages.
  yum: name={{ item }} state=installed
  with_items:
    - python-openstackclient
    - openstack-selinux
    - iptables
    - iptables-services

- name: Copy iptables configure.
  template: src=iptables.j2 dest=/etc/sysconfig/iptables

- name: Ensure base service is stopped and disabled on boot.
  service: name={{ item }} enabled=no state=stopped
  ignore_errors: True
  with_items:
    - NetworkManager
    - firewalld

- name: Ensure base service is started and enabled on boot.
  service: name={{ item }} enabled=yes state=started
  ignore_errors: True
  with_items:
    - iptables
    - network
